### ISSUE TITLE
Referrence error

### ISSUE THREAD

**Issue by hejmadsk** [hejmadsk/markdown-blog#1]
When i add <%= article.title %> to _form_fields.ejs i get an error. When i remove it its ok. I follow the YouTube guide, and he does not have issues. I 32 minutes in.

`ReferenceError: C:\Users\mk\Documents\GitHub\markdown-blog\views\articles\new.ejs:20
    18| 

    19|       <form action="/articles" method="POST">

 >> 20|         <%- include('_form_fields.ejs') %>

    21|       </form>

    22|     </div>

    23|   </body>

C:\Users\mk\Documents\GitHub\markdown-blog\views\articles\_form_fields.ejs:5
    3|   <input

    4|     required

 >> 5|     value="<%= article.title %>"

    6|     type="text"

    7|     name="title"

    8|     id="title"

article is not defined
    at eval ("C:\\Users\\mk\\Documents\\GitHub\\markdown-blog\\views\\articles\\_form_fields.ejs":12:26)
    at _form_fields (C:\Users\mk\Documents\GitHub\markdown-blog\node_modules\ejs\lib\ejs.js:703:17)
    at include (C:\Users\mk\Documents\GitHub\markdown-blog\node_modules\ejs\lib\ejs.js:701:39)
    at eval ("C:\\Users\\mk\\Documents\\GitHub\\markdown-blog\\views\\articles\\new.ejs":12:17)
    at new (C:\Users\mk\Documents\GitHub\markdown-blog\node_modules\ejs\lib\ejs.js:703:17)
    at tryHandleCache (C:\Users\mk\Documents\GitHub\markdown-blog\node_modules\ejs\lib\ejs.js:274:36)
    at View.exports.renderFile [as engine] (C:\Users\mk\Documents\GitHub\markdown-blog\node_modules\ejs\lib\ejs.js:491:10)
    at View.render (C:\Users\mk\Documents\GitHub\markdown-blog\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\mk\Documents\GitHub\markdown-blog\node_modules\express\lib\application.js:657:10)
    at Function.render (C:\Users\mk\Documents\GitHub\markdown-blog\node_modules\express\lib\application.js:609:3)`

**Comment by hejmadsk** [comment]
Ok that particular issue was solved with changing 
`router.get('/new', (req, res) => {
  res.render('articles/new.ejs')
})
`
to  

`router.get('/new', (req, res) => {
  res.render('articles/new.ejs', { article: new Article() })
})
`
